### PR TITLE
update ruamel.yaml to ruamel_yaml

### PR DESCRIPTION
**Pull request by erwanp**
to comply with ruamel>0.15 new API

### CODE REVIEW

**Comment by jiweiqi** [comment]
Thanks for contributing. A quick question about the choice of `ruamel`. Could you provide more details on why we need a new version of `ruamel`?

**Comment by erwanp** [comment]
I wanted to try ReacTorch,  cloned your repo and installed :  I didn't have ruamel  so it was installed automatically through `pip` . The latest version was fetched, whose API changed. 

Alternative : keep the old version but enforce it in the requirements.txt : ruamel<0.15  (a quick research showed me that's when the API changed and broke your package)

Best,

**Comment by jiweiqi** [comment]
I believe `ruamel.yaml` and `rumel_yaml` are two different packages, and changing that could have unexpected behavior at certain situations. It will be great if you can install `ruamel.yaml`. You can installed it via conda as outlined in https://github.com/DENG-MIT/reactorch/wiki/Installation.

**Comment by erwanp** [comment]
Indeed you are right, ruamel_yaml [appears to be just a clone](http://5.9.10.113/64592897/when-should-i-use-ruamel-yaml-vs-ruamel-yaml). 

I'll retry with ruamel.yaml and post the initial Issue I had if it happens again.

We can close here.

**Comment by jiweiqi** [comment]
Sure. Feel free to post if anything I can help.

**Pull request closed without merging**
